### ISSUE TITLE
Loxone communication

### ISSUE THREAD

**Issue by Keany** [seppe912/Midea2Lox#1]
I installed plugin, copied your loxplan to my loxone.

But nothing happens when I try power, or audio etc...

In plugin log i have only status: 
`20.08 15:41 requests.packages.urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): mapp.appsmb.com
20.08 15:41 requests.packages.urllib3.connectionpool DEBUG    https://mapp.appsmb.com:443 "POST /v1/appliance/transparent/send HTTP/1.1" 200 None
20.08 15:41 midea.cloud  INFO     Error ignored: '3176' - 'The asyn reply does not exist '
20.08 15:41 midea.cloud  INFO     Retrying API call: 'appliance/transparent/send'
20.08 15:41 midea.cloud  ERROR    RecursionError: '3176' - 'The asyn reply does not exist '
20.08 15:41 __main__     INFO     Fehler bei send_to_midea, , UEbertragung abgebrochen
20.08 15:41 requests.packages.urllib3.connectionpool DEBUG    Starting new HTTP connection (1): 192.168.1.77
20.08 15:41 requests.packages.urllib3.connectionpool DEBUG    http://192.168.1.77:80 "GET /dev/sps/io/Midea.AC_script/0 HTTP/1.1" 200 111
20.08 15:41 __main__     INFO     ['status']
20.08 15:41 __main__     INFO     Status Update wird gestartet
20.08 15:41 requests.packages.urllib3.connectionpool DEBUG    Starting new HTTP connection (1): 192.168.1.77
20.08 15:41 requests.packages.urllib3.connectionpool DEBUG    http://192.168.1.77:80 "GET /dev/sps/io/Midea.AC_script/1 HTTP/1.1" 200 111
20.08 15:41 midea.cloud  DEBUG    Performs a user login with the credentials supplied to the constructor
20.08 15:41 requests.packages.urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): mapp.appsmb.com
20.08 15:41 requests.packages.urllib3.connectionpool DEBUG    https://mapp.appsmb.com:443 "POST /v1/user/login/id/get HTTP/1.1" 200 None
20.08 15:41 midea.cloud  DEBUG    self.get_login_id: Get the login ID from the email address: '55953f06-f2cb-4ac1-80ce-9e805e435647'
20.08 15:41 midea.cloud  DEBUG    self.login: self.login_id == None - login.self using self.get_login_id
20.08 15:41 requests.packages.urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): mapp.appsmb.com
20.08 15:41 requests.packages.urllib3.connectionpool DEBUG    https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
20.08 15:41 midea.cloud  DEBUG    self.login: self.session: '<midea.cloud.cloud object at 0x761c4390>' - 'None'
20.08 15:41 requests.packages.urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): mapp.appsmb.com
20.08 15:41 requests.packages.urllib3.connectionpool DEBUG    https://mapp.appsmb.com:443 "POST /v1/homegroup/list/get HTTP/1.1" 200 None
20.08 15:41 requests.packages.urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): mapp.appsmb.com
20.08 15:41 requests.packages.urllib3.connectionpool DEBUG    https://mapp.appsmb.com:443 "POST /v1/appliance/list/get HTTP/1.1" 200 None
20.08 15:41 midea.cloud  INFO     Device list: [{'id': '17592186100516', 'activeStatus': '1', 'des': '', 'modelNumber': '8', 'type': '0xAC', 'sn': '4fc72270d7d17bd2b73def822559dd8371a3abdcf2aeedf999cb9c8cd50bdc3322c4ef94e8a7e8d0a94e63983afeb2ee', 'onlineStatus': '1', 'name': 'Klimatizace'}]
20.08 15:41 midea.cloud  DEBUG    Sending to 17592186100516: 5a5a01115700200000000000000000000e031214c679000000050a00000000000000000002000000aa1eac00000000000302408100ff03ff00300000000000000000000003bb8100000000000000000000000000000000
20.08 15:41 requests.packages.urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): mapp.appsmb.com
20.08 15:41 requests.packages.urllib3.connectionpool DEBUG    https://mapp.appsmb.com:443 "POST /v1/appliance/transparent/send HTTP/1.1" 200 None
20.08 15:41 midea.cloud  INFO     Error ignored: '3176' - 'The asyn reply does not exist '
20.08 15:41 midea.cloud  INFO     Retrying API call: 'appliance/transparent/send'
20.08 15:42 requests.packages.urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): mapp.appsmb.com
20.08 15:42 requests.packages.urllib3.connectionpool DEBUG    https://mapp.appsmb.com:443 "POST /v1/appliance/transparent/send HTTP/1.1" 200 None
20.08 15:42 midea.cloud  INFO     Error ignored: '3176' - 'The asyn reply does not exist '
20.08 15:42 midea.cloud  INFO     Retrying API call: 'appliance/transparent/send'
20.08 15:42 requests.packages.urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): mapp.appsmb.com
20.08 15:43 requests.packages.urllib3.connectionpool DEBUG    https://mapp.appsmb.com:443 "POST /v1/appliance/transparent/send HTTP/1.1" 200 None
20.08 15:43 midea.cloud  INFO     Error ignored: '3176' - 'The asyn reply does not exist '
20.08 15:43 midea.cloud  INFO     Retrying API call: 'appliance/transparent/send'
20.08 15:43 requests.packages.urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): mapp.appsmb.com
20.08 15:43 requests.packages.urllib3.connectionpool DEBUG    https://mapp.appsmb.com:443 "POST /v1/appliance/transparent/send HTTP/1.1" 200 None`

What I am doing wrong?

**Comment by seppe912** [comment]
as discussed in https://www.loxwiki.eu/display/LOXBERRY/Midea2Lox , i think there is an failure in your Loxone config. Your Loxone don´t send the korrekt attributes.
