### ISSUE TITLE
I dont see any setting in my plugin

### ISSUE THREAD

**Issue by tvrdas** [seppe912/Midea2Lox#10]
Hello there, i installed plugin, but i dont see any setting after opening it. Tried to reinstall but nothing changed. Any fix for it? 
![obrázok](https://github.com/seppe912/Midea2Lox/assets/163724467/e748dd53-7d76-408f-a642-92de345c4398)

**Comment by regamp** [comment]
I have the same problem. The program cannot install the necessary files.
![error1](https://github.com/seppe912/Midea2Lox/assets/148690439/ff0f5a7f-f91c-4e28-934c-897437943922)
My install log file: 
[2log.txt](https://github.com/user-attachments/files/15587375/2log.txt)

**Comment by seppe912** [comment]
there is something wrong with your loxberry / apt

`Certificate verification failed: The certificate is NOT trusted. The certificate chain uses not yet valid certificate. Could not handshake: Error in the certificate verification. [IP: 193.201.190.174 443]`

Sorry, cant fix that on my side, its an error from Loxberry.

`(invalid for another 2d 13h 56min 11s)`
maybe it will be fixed in 2 days? ;)

**Comment by seppe912** [comment]
this looks like an similar problem:
https://www.loxforum.com/forum/projektforen/loxberry/allgemeines-aa/246364-die-apt-datenbank-konnte-nicht-aktualisiert-werden?p=246458#post246458

maybe this helps?

**Comment by regamp** [comment]
I reinstalled the virtual(proxmox) Loxberry, now it does not install the packages (msmart-ng). I can install other plugins (CalDAV,MotionEye,Weather4Loxone), but not Midea2Lox. On Dietpi I was able to install msmart-ng and it works fine. 
[Log.txt](https://github.com/user-attachments/files/15663191/Log.txt)

**Comment by seppe912** [comment]
a fresh installed vm ware with an loxberry 3.0: no problems.
[gIXV3c75b5.log](https://github.com/user-attachments/files/15683621/gIXV3c75b5.log)

Maybe there is an error on your VM... i dont know why. 
anyway, now your apt error is gone. You have an problem with pip ssl.. Normaly it will be installed as standard in the venv on loxberry/bin/pluins/Midea2Lox/
which pakages are installed on your system? This packages will be installed on my new system:
![image](https://github.com/seppe912/Midea2Lox/assets/39451979/318e97f7-05a2-4a73-a855-0537f5792864)

i think certifi is the one for ssl connections.
Try this one, it will install certifi again before the ssl connection will be set, maybe it will work!?:
[Midea2Lox-3.3.3 certifi.zip](https://github.com/user-attachments/files/15685428/Midea2Lox-3.3.3.certifi.zip)

i install the python packages from piwheels which is much faster to install on Raspberry. if the above try will not work, you can try to install the packages from the standard source..
you need to change the Postinstall.sh as follow:

from:
```
...
pip3 install --upgrade pip
pip3 install --upgrade pip setuptools wheel
pip3 install requests --extra-index-url https://www.piwheels.org/simple --prefer-binary
pip3 install "paho-mqtt<2.0.0" --extra-index-url https://www.piwheels.org/simple --prefer-binary
pip3 install ifaddr --extra-index-url https://www.piwheels.org/simple --prefer-binary
pip3 install msmart-ng==2023.11.0 --extra-index-url https://www.piwheels.org/simple --prefer-binary
...
```
to
```
...
pip3 install --upgrade pip
pip3 install --upgrade pip setuptools wheel
pip3 install requests
pip3 install "paho-mqtt<2.0.0"
pip3 install ifaddr
pip3 install msmart-ng==2023.11.0
...
```

ive updatet another package for you, with the above changes. Maybe it helps on your virtual machine..
[Midea2Lox-3.3.3 without pywheels.zip](https://github.com/user-attachments/files/15685442/Midea2Lox-3.3.3.without.pywheels.zip)
But the installtime can be extremly long..

**Comment by seppe912** [comment]
is it working now? when yes, with what change?

**Comment by regamp** [comment]
I tried without pywheels and with certifi ,but didn't helped.
3.3.3 doesn't work, but 3.2.5 boots and can be discovered. Maybe it's because of OpenSSL or (pyhton 3.9) , it writes log that SSL error.
 I tried in Virtualbox and VMWare but always the same error.
Here is a log file on a brand new loxberry:
[dDGK1GwxnQ.log](https://github.com/user-attachments/files/15918593/dDGK1GwxnQ.log)

**Comment by seppe912** [comment]
yes, there is something wrong with your ssl on your machine.
ißve updated msmart now to the lates release, maybe there is anything different, i dont know. 
Ive marked it as PreRelease, as i dont know exactly which changes are done in msmart, maybe there is more error possible..

**Comment by seppe912** [comment]
please try the lates preRelease. The issue seems to be on Systems that allready have an Pythonversion >3.9 installed. 
The Installation from an lower Python Version (3.9) seems to break the SSL configuration. 
The lates fix will use the allready installed PythonVersion if its >3.9.

**Comment by regamp** [comment]
Now its working for me. Thank you.
