### ISSUE TITLE
on Update -> 3.3.4 No Module MSSMART found

### ISSUE THREAD

**Issue by elixier** [seppe912/Midea2Lox#11]
28.06 21:00 Midea2Lox.py ERROR '2'
28.06 21:00 Midea2Lox.py DEBUG 13.24s
28.06 22:21 Midea2Lox.py ERROR (, ModuleNotFoundError("No module named 'msmart'"), )
28.06 22:25 Midea2Lox.py ERROR (, ModuleNotFoundError("No module named 'msmart'"), )
28.06 22:26 Midea2Lox.py ERROR (, ModuleNotFoundError("No module named 'msmart'"), )
28.06 22:26 Midea2Lox.py ERROR (, ModuleNotFoundError("No module named 'msmart'"), )
28.06 22:26 Midea2Lox.py ERROR (, ModuleNotFoundError("No module named 'msmart'"), )

**Comment by seppe912** [comment]
can you upload the install log please?

**Comment by elixier** [comment]
[Midea2Lox.log](https://github.com/user-attachments/files/16120872/Midea2Lox.log)

gerne

**Comment by seppe912** [comment]
auch der SSL Fehler, bitte mal das letzte PreRelease testen, das sollte funktionieren.

**Comment by elixier** [comment]
Danke dir! 3.3.5 funktioniert!
