### ISSUE TITLE
No Status Feedback on V3.3.5

### ISSUE THREAD

**Issue by elixier** [seppe912/Midea2Lox#12]
09.07 16:05 msmart.lan DEBUG Received data from 10.10.11.203:6444: xxx
09.07 16:05 msmart.lan DEBUG Received packet from 10.10.11.203:6444: xxx
09.07 16:05 msmart.lan DEBUG Received response from 10.10.11.203:6444: xxx
09.07 16:05 msmart.base_device DEBUG Response from 10.10.11.203:6444 in 1.640000 seconds.
09.07 16:05 msmart.device.AC.command DEBUG State response payload: xxx
09.07 16:05 Midea2Lox.py INFO Statusupdate for Midea.meineID @ 10.10.11.203 successful. Runtime: 11.65s
09.07 16:05 Midea2Lox.py ERROR '1'
09.07 16:05 Midea2Lox.py DEBUG 11.65s

Nun kommt beim Status-Update nichts mehr zurück. Wenn ich irgendwie unterstützen kann, gib gerne Bescheid.

**Comment by seppe912** [comment]
Kann aus dem log wenig rauslesen. Sieht so aus als ob Daten von der Klima ankommen( gehe davon aus du hast die Daten mit xxx ersetzt), dann sollten die Loxone eingänge gesetzt werden, dort geht wohl was nicht. Steht aber nicht genauer dabei.
Da der Code zum setzen von Loxone Eingängen schon seit Ewigkeiten nicht geändert wurde glaube ich jetzt eher mal an andere Einflüsse.
Evtl mal Loxone und loxberry neu starten. Wie setzt du deine Eingänge? Per mqtt? Steht das auch am Anfang im log wenn du midea2lox startest? Kommen werte am mqtt Gateway an?

**Comment by elixier** [comment]
Ja, die habe ich mit der ID ersetzt. Es sind auch noch alte Daten von einer früheren Midea2Lox-Version gesetzt, hat also auch mal funktioniert.
Das einzige was über MQTT ankommt ist Midea2Lox/connection/status, das wird auch schön an dem virtuellen Eingang gesetzt. 
Mhhh, weiß für heute nicht weiter. Loxberry habe ich neugestartet, Miniserver heute Nacht ungern. Habe aber auch schon den Midea2Lox_Midea_xxx_power_state gelöscht und neu angelegt.

09.07 22:46 Midea2Lox.py DEBUG Debug is True
09.07 22:46 Midea2Lox.py INFO got MQTT Settings - publish over MQTT except on Midea2Lox support_mode
09.07 22:46 asyncio DEBUG Using selector: EpollSelector
09.07 22:46 Midea2Lox.py INFO MQTT: Verbindung akzeptiert
09.07 22:46 Midea2Lox.py INFO Midea2Lox Version: 3.3.5 msmart Version: 2024.5.4
09.07 22:46 Midea2Lox.py DEBUG Publishing: MsgNum:1: 'Midea2Lox/connection/status','connected'
09.07 22:46 Midea2Lox.py INFO Socket bind complete, listen at 10.10.11.21:7013
09.07 22:53 Midea2Lox.py DEBUG Debug is True
09.07 22:53 Midea2Lox.py INFO got MQTT Settings - publish over MQTT except on Midea2Lox support_mode
09.07 22:53 asyncio DEBUG Using selector: EpollSelector
09.07 22:53 Midea2Lox.py INFO MQTT: Verbindung akzeptiert

**Comment by seppe912** [comment]
Ja habe den Fehler gefunden, in Python 3.11 werden die Werte von den Klassen zurückgegeben, nichtmehr die Namen... damit konnte SendToLoxone nix anfangen. Ich habe mal auf die schnelle einen Versuch als Prerelease hochgeladen, sollte nun klappen !?

**Comment by elixier** [comment]
Sehr gut, es funktioniert wieder! 👍 
Was wäre da eigentlich Best Practice zum aktualisieren? Impuls alle 30sek + wenn Online auf Aktualisieren?

**Comment by seppe912** [comment]
Danke für die Rückmeldung.
Ich denke da gibt’s keine best practice. Je nachdem wie aktuell und wann du die Werte brauchst musst/kannst du abfragen.
