### ISSUE TITLE
OSK-105 Supported?

### ISSUE THREAD

**Issue by iwan75** [seppe912/Midea2Lox#4]
i have an OSK-105. with this i can youse the same midea app.
does the plugin work for this as well?

when i discover my devices i can see in de debug-log my 2 devices, but in de plugin they are not listed.

logfile attached...
[midea2lox.log](https://github.com/seppe912/Midea2Lox/files/12292181/midea2lox.log)

**Comment by seppe912** [comment]
in your logs you have an error regarding the API changes. Please Try the latest PreRelease, maybe it will work, i dont know because i dont have an OSK-105. If 105 is not supported, changes in msmart has to be done. I cant do that.
