### ISSUE TITLE
Sk-103x discovery in 3.3.1

### ISSUE THREAD

**Issue by RobW78** [seppe912/Midea2Lox#7]
Hello togehter,

I might missunderstand something or I found maybe a constellation that has not  been considert yet...?

I use a EU-SK103x stick inside my Midea unit from august23. Cloud operation is working normaly.
Discovery from Loxberry Midea Gui is not discovering, finding the device.

However the **settings metioned in the manual** regarding tocken is not showing on screen:

```
"Installation

Nach der Installation Miniserver auswählen und UDP Port eintragen. → Speichern und neustart drücken.
Discover: Um vorhandene Klimaanlagen zu finden **müssen die Zugangsdaten zur Mideacloud angegeben werden**. Anschließend werden über Discover alle im Lan befindlichen Geräte angezeigt und die Daten abgespeichert (werden zur Steuerung benötigt)
Konfigurationsoptionen

UDP Port frei wählbar, muss mit gewählten Port von Loxone übereinstimmen. Standard 7013
**MideaCloud User/Passwort → notwendig um den Token für V3 sticks zu bekommen**"

```
 What I else find strange is, that if i ping the Midea from the loxberry system.... it takes many attemps to reply on the ping, even if the system is in the same subnet. 
Once the first ping request is answerd, the connection is quite solid and fast !?

Maybe you have a hint, there my failure might be ?

BR
Robert

![IMG_8452](https://github.com/seppe912/Midea2Lox/assets/148754043/6e02ff3d-0804-472f-9bc3-90dda4bbcbba)
![Midea2Lox_103x_a](https://github.com/seppe912/Midea2Lox/assets/148754043/cbc816ff-0c3b-4be2-b6b1-edf97eb0a9b1)

[midea2lox(1).log](https://github.com/seppe912/Midea2Lox/files/13078481/midea2lox.1.log)

**Comment by seppe912** [comment]
maybe its just a bad wifi connection? Sorry i dont have any ideas about that..
