### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by regamp** [seppe912/Midea2Lox#8]
Hi,
 After Discover, the log file throws  errors. Maybe I did something wrong. Version: 3.3.1  loxberry 3.0.6 in VM

![Kjs](https://github.com/seppe912/Midea2Lox/assets/148690439/23c18605-dd35-4df1-8af6-29d2a1d23bf8)

Log file.
![error](https://github.com/seppe912/Midea2Lox/assets/148690439/c517e8bb-3c76-43cb-adce-5eaa3a1d1309)

**Comment by seppe912** [comment]
Ive pre-released a new Version with msmart 2023.11.0. This should fix your problem. But i havent tested it with Midea2Lox. It should work, but msmart has done some changes on fanspeed, maybe there are some problems.. so both Versions will be online.
f youre able to discover your devices with the pre release, save your device config from loxberry. you can use it with the Release Version of Midea2Lox.
